SELECT USER_ID, USERNAME, CREATED, PASSWORD_CHANGE_DATE
FROM USER_USERS;
SELECT * FROM USER_TABLES;
DESC ORDERS;
DESC PRODUCTLIST;
DESC REVIEWS;
DESC STOREFRONT;
DESC USERBASE;
DESC USERLIBRARY;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTLIST;
SELECT * FROM REVIEWS;
SELECT * FROM STOREFRONT;
SELECT * FROM USERBASE;
SELECT * FROM USERLIBRARY;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS;
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;
SELECT USERNAME
FROM USERBASE
ORDER BY USERNAME;
SELECT FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL
FROM USERBASE
WHERE EMAIL LIKE '%yahoo%';
SELECT USERNAME, BIRTHDAY, WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS < 25;
SELECT USERID, PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED > 100;